name: test

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'
      - name: lint check
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'
      - name: Build app
        run: go build -v -o test ./main.go